"""empty message

Revision ID: f4452a88a300
Revises: 28c0ed97f2e1
Create Date: 2024-04-27 02:01:39.132420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4452a88a300'
down_revision = '28c0ed97f2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eyes_color',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('opening_crawl',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('producer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('average_height',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('eye_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('hair_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('skin_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('starship_class',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('hyperdrive_rating',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('MGLT',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('vehicle_class',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('vehicle_class',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('consumables',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('MGLT',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('hyperdrive_rating',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('max_atmosphering_speed',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('passengers',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('crew',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cost_in_credits',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('starship_class',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('skin_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('hair_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('eye_colors',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('average_height',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('classification',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('producer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('opening_crawl',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('eyes_color',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
